### ISSUE TITLE
Peer to peer code review 

### ISSUE THREAD

**Issue by Benmuiruri** [deyemiobaa/CC-global-summit#2]
Hi @deyemiobaa great job on the project. It looks almost identical to Behance template. 

- In particular, great job on loading the speakers' section dynamically. 
### Optional change

- Great job using font-awesome to add the [nav tags](https://github.com/deyemiobaa/CC-global-summit/blob/main/index.html#L17). I would suggest adding a span tag that describes the font-awesome icon for non-visual users to increase the accessibility of your website. 
- You could do something like 
`<li>
         <a href="" target="_blank"
            ><i class="fa-brands fa-linkedin" aria-hidden="true"></i>
            <span class="sr-only">LinkedIn</span></a
          >
        </li>`

**Comment by deyemiobaa** [comment]
Thank you, Ben. For this awesome review. I've implemented the changes as you suggested
